// generated by build-custom-entities.js, do not edit
#ifndef _H_GL_CUSTOM_ENTITIES
#define _H_GL_CUSTOM_ENTITIES
#include "../../surface.h"

#define GL_CUSTOM_ENTITY_ANIM_COUNT 59
#define GL_CUSTOM_ENTITY_FRAMES_PER_ANIM 18
#define GL_CUSTOM_ENTITY_SLOT_COUNT 1062
#define GL_CUSTOM_ENTITY_FILE_BASE 4032

typedef struct gl_custom_entity_geom {
    unsigned short w, h, full_w, full_h;
    short offset_x, offset_y;
} gl_custom_entity_geom;

typedef struct gl_custom_entity_anim {
    const char *name;
    unsigned int colour;
    unsigned short file_id;
} gl_custom_entity_anim;

extern gl_atlas_position gl_custom_entity_atlas_positions[GL_CUSTOM_ENTITY_SLOT_COUNT];
extern const gl_custom_entity_geom gl_custom_entity_geoms[GL_CUSTOM_ENTITY_SLOT_COUNT];
extern const gl_custom_entity_anim gl_custom_entity_anims[GL_CUSTOM_ENTITY_ANIM_COUNT];

#endif
