// generated by build-custom-content.js, do not edit
#ifndef _H_GL_CUSTOM
#define _H_GL_CUSTOM
#include "../../surface.h"

#define GL_CUSTOM_SPRITE_COUNT 319
#define GL_CUSTOM_SPRITE_BASE 450

// OpenRSC rank crowns share this atlas, packed after item icons
#define GL_CUSTOM_CROWN_BASE 752
#define GL_CUSTOM_CROWN_COUNT 5

// bank preset viewer's equipment placeholders, packed after the crowns
#define GL_CUSTOM_EQUIPSLOT_BASE 757
#define GL_CUSTOM_EQUIPSLOT_COUNT 12
#define GL_CUSTOM_EQUIPSLOT_HIGHLIGHT 11

typedef struct {
    unsigned short slot;
    unsigned short width;
    unsigned short height;
} gl_custom_equipslot_geom;

extern const gl_custom_equipslot_geom
    gl_custom_equipslot_geoms[GL_CUSTOM_EQUIPSLOT_COUNT];

typedef struct {
    unsigned short slot;
    unsigned short width;
    unsigned short height;
} gl_custom_crown_geom;

extern const gl_custom_crown_geom gl_custom_crown_geoms[GL_CUSTOM_CROWN_COUNT];

extern gl_atlas_position gl_custom_atlas_positions[GL_CUSTOM_SPRITE_COUNT];

#endif
