// generated by build-custom-content.js, do not edit
#ifndef _H_CUSTOM_DEFS
#define _H_CUSTOM_DEFS
#include "surface.h"
void game_data_append_custom(void);
void game_data_append_custom_objects(void);
void surface_setup_custom_item_sprites(Surface *surface, int sprite_item_base);
#if defined(RENDER_GL) || defined(RENDER_3DS_GL)
// populate surface geometry for the custom worn-equipment / no-body-NPC sprite range, GL-only
void surface_setup_custom_entity_sprites(Surface *surface);
#endif
#endif
