#include "protocol177.h"

// literal opcode values on both sides, generated by matching names between the 204 and 177 headers

int protocol177_client_opcode(int opcode) {
    switch (opcode) {
    case 235: return 236; // CLIENT_APPEARANCE
    case 212: return 207; // CLIENT_BANK_CLOSE
    case 23:  return 205; // CLIENT_BANK_DEPOSIT
    case 22:  return 206; // CLIENT_BANK_WITHDRAW
    case 158: return 221; // CLIENT_CAST_GROUND
    case 249: return 224; // CLIENT_CAST_GROUNDITEM
    case 4:   return 220; // CLIENT_CAST_INVITEM
    case 50:  return 225; // CLIENT_CAST_NPC
    case 99:  return 222; // CLIENT_CAST_OBJECT
    case 229: return 226; // CLIENT_CAST_PLAYER
    case 137: return 227; // CLIENT_CAST_SELF
    case 180: return 223; // CLIENT_CAST_WALLOBJECT
    case 25:  return 25; // CLIENT_CHANGE_PASSWORD
    case 216: return 3; // CLIENT_CHAT
    case 116: return 237; // CLIENT_CHOOSE_OPTION
    case 31:  return 1; // CLIENT_CLOSE_CONNECTION
    case 29:  return 231; // CLIENT_COMBAT_STYLE
    case 38:  return 7; // CLIENT_COMMAND
    case 176: return 199; // CLIENT_DUEL_ACCEPT
    case 77:  return 198; // CLIENT_DUEL_CONFIRM_ACCEPT
    case 197: return 203; // CLIENT_DUEL_DECLINE
    case 33:  return 201; // CLIENT_DUEL_ITEM_UPDATE
    case 8:   return 200; // CLIENT_DUEL_OPTIONS
    case 195: return 26; // CLIENT_FRIEND_ADD
    case 167: return 27; // CLIENT_FRIEND_REMOVE
    case 247: return 252; // CLIENT_GROUNDITEM_TAKE
    case 132: return 29; // CLIENT_IGNORE_ADD
    case 241: return 30; // CLIENT_IGNORE_REMOVE
    case 90:  return 246; // CLIENT_INVENTORY_COMMAND
    case 246: return 251; // CLIENT_INVENTORY_DROP
    case 170: return 248; // CLIENT_INVENTORY_UNEQUIP
    case 169: return 249; // CLIENT_INVENTORY_WEAR
    case 163: return 254; // CLIENT_KNOWN_PLAYERS
    case 0:   return 0; // CLIENT_LOGIN
    case 102: return 6; // CLIENT_LOGOUT
    case 190: return 244; // CLIENT_NPC_ATTACK
    case 202: return 195; // CLIENT_NPC_COMMAND
    case 153: return 245; // CLIENT_NPC_TALK
    case 136: return 242; // CLIENT_OBJECT_COMMAND1
    case 79:  return 230; // CLIENT_OBJECT_COMMAND2
    case 3:   return 3; // CLIENT_PACKET_EXCEPTION, unused on 177
    case 67:  return 5; // CLIENT_PING
    case 171: return 228; // CLIENT_PLAYER_ATTACK
    case 103: return 204; // CLIENT_PLAYER_DUEL
    case 165: return 214; // CLIENT_PLAYER_FOLLOW
    case 142: return 235; // CLIENT_PLAYER_TRADE
    case 218: return 28; // CLIENT_PM
    case 254: return 211; // CLIENT_PRAYER_OFF
    case 60:  return 212; // CLIENT_PRAYER_ON
    case 2:   return 2; // CLIENT_REGISTER
    case 206: return 51; // CLIENT_REPORT_ABUSE, 206 is BANK_WITHDRAW in 177
    case 111: return 213; // CLIENT_SETTINGS_GAME
    case 64:  return 31; // CLIENT_SETTINGS_PRIVACY
    case 236: return 217; // CLIENT_SHOP_BUY
    case 166: return 218; // CLIENT_SHOP_CLOSE
    case 221: return 216; // CLIENT_SHOP_SELL
    case 45:  return 193; // CLIENT_SLEEP_WORD
    case 55:  return 232; // CLIENT_TRADE_ACCEPT
    case 104: return 202; // CLIENT_TRADE_CONFIRM_ACCEPT
    case 230: return 233; // CLIENT_TRADE_DECLINE
    case 46:  return 234; // CLIENT_TRADE_ITEM_UPDATE
    case 53:  return 250; // CLIENT_USEWITH_GROUNDITEM
    case 91:  return 240; // CLIENT_USEWITH_INVITEM
    case 135: return 243; // CLIENT_USEWITH_NPC
    case 115: return 241; // CLIENT_USEWITH_OBJECT
    case 113: return 219; // CLIENT_USEWITH_PLAYER
    case 161: return 239; // CLIENT_USEWITH_WALLOBJECT
    case 187: return 194; // CLIENT_WALK
    case 16:  return 215; // CLIENT_WALK_ACTION
    case 14:  return 238; // CLIENT_WALL_OBJECT_COMMAND1
    case 127: return 229; // CLIENT_WALL_OBJECT_COMMAND2
    default:
        // opcodes with no 177 equivalent, or already raw 177 values, pass through unchanged
        return opcode;
    }
}

int protocol177_server_opcode(int opcode) {
    switch (opcode) {
    case 239: return 59; // SERVER_APPEARANCE
    case 221: return 203; // SERVER_BANK_CLOSE
    case 222: return 42; // SERVER_BANK_OPEN
    case 214: return 249; // SERVER_BANK_UPDATE
    case 9:   return 4; // SERVER_CLOSE_CONNECTION
    case 209: return 210; // SERVER_DUEL_ACCEPTED
    case 218: return 225; // SERVER_DUEL_CLOSE
    case 208: return 172; // SERVER_DUEL_CONFIRM_OPEN
    case 219: return 176; // SERVER_DUEL_OPEN
    case 210: return 253; // SERVER_DUEL_RECIPIENT_ACCEPTED
    case 215: return 30; // SERVER_DUEL_SETTINGS
    case 216: return 6; // SERVER_DUEL_ITEMS
    case 23:  return 71; // SERVER_FRIEND_LIST
    case 28:  return 120; // SERVER_FRIEND_MESSAGE
    case 24:  return 149; // SERVER_FRIEND_STATUS_CHANGE
    case 228: return 240; // SERVER_GAME_SETTINGS
    case 26:  return 109; // SERVER_IGNORE_LIST
    case 252: return 53; // SERVER_INVENTORY_ITEMS
    case 212: return 123; // SERVER_INVENTORY_ITEM_REMOVE
    case 213: return 90; // SERVER_INVENTORY_ITEM_UPDATE
    case 10:  return 183; // SERVER_LOGOUT_DENY
    case 8:   return 131; // SERVER_MESSAGE
    case 246: return 245; // SERVER_OPTION_LIST
    case 245: return 252; // SERVER_OPTION_LIST_CLOSE
    case 241: return 83; // SERVER_PLAYER_DIED
    case 226: return 5; // SERVER_PLAYER_QUEST_LIST
    case 242: return 153; // SERVER_PLAYER_STAT_EQUIPMENT_BONUS
    case 220: return 33; // SERVER_PLAYER_STAT_EXPERIENCE_UPDATE
    case 202: return 114; // SERVER_PLAYER_STAT_FATIGUE
    case 200: return 244; // SERVER_PLAYER_STAT_FATIGUE_ASLEEP
    case 243: return 156; // SERVER_PLAYER_STAT_LIST
    case 211: return 159; // SERVER_PLAYER_STAT_UPDATE
    case 227: return 206; // SERVER_PRAYER_STATUS
    case 27:  return 51; // SERVER_PRIVACY_SETTINGS
    case 240: return 211; // SERVER_REGION_ENTITY_UPDATE
    case 254: return 99; // SERVER_REGION_GROUND_ITEMS
    case 248: return 79; // SERVER_REGION_NPCS
    case 247: return 104; // SERVER_REGION_NPC_UPDATE
    case 253: return 48; // SERVER_REGION_OBJECTS
    case 255: return 191; // SERVER_REGION_PLAYERS
    case 250: return 234; // SERVER_REGION_PLAYER_UPDATE
    case 249: return 91; // SERVER_REGION_WALL_OBJECTS
    case 204: return 89; // SERVER_SERVER_MESSAGE
    case 203: return 222; // SERVER_SERVER_MESSAGE_ONTOP
    case 233: return 137; // SERVER_SHOP_CLOSE
    case 234: return 101; // SERVER_SHOP_OPEN
    case 199: return 84; // SERVER_SLEEP_CLOSE
    case 198: return 194; // SERVER_SLEEP_INCORRECT
    case 201: return 117; // SERVER_SLEEP_OPEN
    case 207: return 204; // SERVER_SOUND
    case 206: return 36; // SERVER_MAGIC_BUBBLE
    case 237: return 128; // SERVER_TRADE_CLOSE
    case 217: return 20; // SERVER_TRADE_CONFIRM_OPEN
    case 236: return 97; // SERVER_TRADE_ITEMS
    case 238: return 92; // SERVER_TRADE_OPEN
    case 235: return 162; // SERVER_TRADE_RECIPIENT_ACCEPTED
    case 229: return 15; // SERVER_TRADE_ACCEPTED
    case 205: return 182; // SERVER_WELCOME
    case 244: return 25; // SERVER_WORLD_INFO
    default:
        return -1; // no 204 equivalent: ignore the packet
    }
}
